#!/usr/bin/env bash
# Install command-line wrappers and app-menu entries for the tools listed in
# desktop/launchers.tsv, so they can be started from anywhere on a Linux
# desktop. Rerun after pulling; it overwrites what it wrote before.
#
#   desktop/install-launchers.sh            install into ~/.local/bin + app menu
#   desktop/install-launchers.sh --remove   remove them again
#
# Each wrapper runs the tool's default environment from this checkout with
# `pixi run --frozen`: exactly what pixi.lock pins, never re-solved. pixi
# picks the CUDA or CPU build from the machine's GPU. The first launch of a
# tool installs its environment (several GB).
set -euo pipefail

REPO=$(cd "$(dirname "$0")/.." && pwd -P)
BIN="${XDG_BIN_HOME:-$HOME/.local/bin}"
APPS="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
MARK="# generated by AI_tools_pixi/desktop/install-launchers.sh"

remove=false
[ "${1:-}" = "--remove" ] && remove=true
mkdir -p "$BIN" "$APPS"

while read -r name tool label cmd; do
    case "$name" in ''|'#'*) continue ;; esac
    wrapper="$BIN/$name"
    desktop="$APPS/ai-tools-$name.desktop"

    if $remove; then
        grep -qs "$MARK" "$wrapper" && rm -v "$wrapper"
        grep -qs "$MARK" "$desktop" && rm -v "$desktop"
        continue
    fi

    cat > "$wrapper" <<EOF
#!/usr/bin/env bash
$MARK
# $tool. Extra arguments go to \`$cmd\`.
# Qt apps under Wayland: PyOpenGL picks EGL, where vispy (napari) finds no GL
# context. XWayland + GLX works; a value set by the caller wins.
export QT_QPA_PLATFORM="\${QT_QPA_PLATFORM:-xcb}" PYOPENGL_PLATFORM="\${PYOPENGL_PLATFORM:-glx}"
exec pixi run --frozen --manifest-path "$REPO/$tool/pixi.toml" $cmd "\$@"
EOF
    chmod +x "$wrapper"
    echo "installed $wrapper"

    [ "$label" = "-" ] && continue
    cat > "$desktop" <<EOF
[Desktop Entry]
$MARK
Type=Application
Name=${label//_/ }
Comment=$tool (AI_tools_pixi)
Exec=$wrapper
Icon=applications-science
Terminal=false
Categories=Science;
EOF
    echo "installed $desktop"
done < "$REPO/desktop/launchers.tsv"

if command -v update-desktop-database >/dev/null; then
    update-desktop-database "$APPS" 2>/dev/null || true
fi
case ":$PATH:" in *":$BIN:"*) ;; *) echo "note: $BIN is not on PATH" ;; esac
